- .bumpversion.cfg
- setup.py
- xmitgcm/__init__.py
> First version

- xmitgcm/variables.py
This could still use a test, but it is a quick fix for trying to read ptracers.
> added ptracer metadata

- xmitgcm/mds_store.py
- xmitgcm/test/test_mds_store.py
- xmitgcm/utils.py
> fixed bug with no_meta dimensions

- doc/index.rst
- xmitgcm/default_diagnostics.py
- xmitgcm/mds_store.py
- xmitgcm/test/test_mds_store.py
- xmitgcm/utils.py
This will be useful for LLC and other cases where there is no available_diagnostics.log file.
> got defaults to work

- xmitgcm/mds_store.py
no tests unfortunately...but at least it doesn't break anything
> added ignore_pickup behavior

- xmitgcm/mds_store.py
This is unfortunately not caught by tests
> fixed little bug

- xmitgcm/llc_utils.py
- xmitgcm/mds_store.py
- xmitgcm/test/test_mds_store.py
- xmitgcm/utils.py
This is a pretty major refactor of how the llc data is read. We now construct a fancy dask graph to load the data in face / level chunks.
> Wrap data with dask

- xmitgcm/mds_store.py
- xmitgcm/variables.py
This helps deal with the LLC output which was saved with unconventional variable names and no meta files.
> added extra variable names

- xmitgcm/test/test_mds_store.py
> add swap_dims test

- xmitgcm/test/test_mds_store.py
- xmitgcm/utils.py
Some tweaks to how reading works.
> updated reading methods and tests

- .bumpversion.cfg
- doc/development.rst
- setup.py
- xmitgcm/__init__.py
> Bump version: 0.1.0 → 0.2.0

- doc/development.rst
- xmitgcm/mds_store.py
- xmitgcm/test/test_mds_store.py
- xmitgcm/variables.py
Will enable better compatibility with xgcm.
> Comodo metadata

- xmitgcm/variables.py
This adds the `axis` and `c_grid_axis_shift` attributes to layers coordinates to ensure compatibility with xgcm.
> layers axis attribute

- .travis.yml
- ci/environment-py36.yml
This PR will add testing of python 3.6, which will hopefully help reveal what is going on in #51.
cc: @sambarluc
> add python 3.6 testing

- xmitgcm/mds_store.py
- xmitgcm/variables.py
Added KPP vars metadata into a new dictionary. This dictionary can potentially be expanded in the future with other such package variables. 
Tests have not been added for these variables, will be subject of a future PR.
> Kpp added properly

- xmitgcm/test/test_mds_store.py
I refactored @sambarluc's test into one single test, which mysteriously is now passing on my machine. I want to see the result on travis.
> test refactor

- xmitgcm/mds_store.py
- xmitgcm/test/test_mds_store.py
> fix specifying nz only

- xmitgcm/mds_store.py
- xmitgcm/test/test_mds_store.py
> Fix llc chunking

- xmitgcm/mds_store.py
- xmitgcm/test/test_mds_store.py
#60 forgot to remove attributes from time after decoding
> fix time encoding

- xmitgcm/mds_store.py
pass py.test in anaconda2 and anaconda3
> fix the problem with testing type of prefix

- MANIFEST.in
- doc/environment.yml
on local machine sphinx 1.7.5 and numpydoc 0.7 work together.
need to update in environment.yml ?
also spotted a typo
> fix for RTD ? fix #75

- xmitgcm/test/test_utils.py
- xmitgcm/utils.py
> fix token bug

- xmitgcm/test/test_utils.py
- xmitgcm/utils.py
sorry I missed that! that was a stupid bug that affected only padded grids.
> silly bug read grid

- xmitgcm/test/test_utils.py
- xmitgcm/utils.py
allow to rebuild facets, rebuild compact form and write to file
testing almost finished
> Write binary files from xmitgcm

- README.rst
updated links to https where possible.
> update links to https

- xmitgcm/mds_store.py
- xmitgcm/test/test_mds_store.py
This is an update to #141 which fixes a bug and adds a test.
> also search in grid_dir for avail_diags.log

- doc/llcreader.rst
- xmitgcm/llcreader/__init__.py
This adds the function `faces_dataset_to_latlon` to the public API and documentation of the llc module.
> add API docs for faces_dataset_to_latlon

- xmitgcm/utils.py
> Make dask and mmap mutually exclusive

- ci/environment-py27.yml
- ci/environment-py36-xarraymaster.yml
- ci/environment-py36.yml
- xmitgcm/mds_store.py
- xmitgcm/test/test_mds_store.py
- xmitgcm/test/test_xmitgcm_common.py
> Modify datetime decoding

- xmitgcm/llcreader/known_models.py
- xmitgcm/llcreader/stores.py
> Fix path join bug

- xmitgcm/mds_store.py
> remove extra print statement from `open_mdsdataset`

- xmitgcm/llcreader/known_models.py
- xmitgcm/llcreader/llcmodel.py
> Add mask_override option to llcreader

- .travis.yml
- ci/environment-py37.yml
- ci/environment-py38.yml
- setup.py
- xmitgcm/mds_store.py
Updated some functions that had deprecation warnings.
> Python 3.8 compatibility

- xmitgcm/llcreader/known_models.py
> #193: New iter_stop matches last model date

- xmitgcm/llcreader/known_models.py
- xmitgcm/llcreader/llcmodel.py
- xmitgcm/test/test_llcreader.py
Fixes #207.
This also unearthed a bug that allowed me to remove some unused code paths.
> add xg and yg to llcreader known_models

- xmitgcm/llcreader/llcmodel.py
- xmitgcm/test/test_llcreader.py
I realized that the dimension coordinate metadata was not being added to llcreader.
> add metadata to llcreader dimensions

- xmitgcm/test/test_utils.py
- xmitgcm/utils.py
> added fix for reading mds data with a large number of vertical levels.
