MITgcm/xmitgcm

xmitgcm/mds_store.py
xmitgcm/test/test_mds_store.py

I was getting errors when trying to swap dims due to the presence of coordinate variables. Solution is to be careful about the order of operations.
Should have been covered by the test suite but was not. Need to add more tests of that logic.

fix bug related to coordinates and dim swapping

---

xmitgcm/mds_store.py
xmitgcm/test/test_mds_store.py

I added the function fix_inconsistent_variables to add the extra row onto drC.  This function is called after the data is read from the mds files but before the data is read into the xarray dataset.  Trying to change the drC array once it is in the xarray dataset causes problems, because xarray generates an error because the shape is different to what it expects.
I also changed read_grid=False to True on Line 165, as this seems to override the choice made when the user calls the function and so the grid wasn't being read.  I'm not sure what this should be in general.

Added fix_inconsistent_variables

---

doc/index.rst
xmitgcm/mds_store.py
xmitgcm/test/test_mds_store.py
xmitgcm/variables.py

I added an option to separately deal with Cartesian curvilinear grids. The only difference with standard Cartesian is that sine/cosine defining the grid rotation at each point are now being read.

Added option for curvilinear grid, including rotation angles of grid

---

xmitgcm/mds_store.py
xmitgcm/test/test_mds_store.py
xmitgcm/utils.py

* Check the default_dtype to add if necessary the default endian
* Modify the IOError when the metadata is absent and the default_dtype is needed
* Add a test to check if an IOError is correctly raised when there is no metadata and default_dtype is None

Slight modifications to improve the use of the default_dtype parameter

---

xmitgcm/mds_store.py
xmitgcm/test/test_mds_store.py

This makes sure we have integer indices for llc grids.

fix j dim datatype for llc grids

---

xmitgcm/test/test_mds_store.py

8 tests which either open or open+print a dataset in 4 different ways, always using `ref_date`, plus `read_grid=True/False` and `read_grid=True, swap_dims=True/False`

Tests for ref_date issue

---

xmitgcm/mds_store.py

The purpose of this modification is to be able to load iteration numbers when file format that are NOT `*.??????????.data`.
You may for example use `_get_all_iternums` as a utility function in order to get iteration numbers of for compressed files with calls of this type:
```
iters = xmitgcm.mds_store._get_all_iternums(data_dir, file_prefixes=varname, file_format='*.??????????.data.shrunk')
```

Generalizes _get_all_iternums in order to handle compressed data

---

xmitgcm/mds_store.py

As described in #78, it's possible to get an obtuse error message when attempting to load in multiple timestamps with a single `prefix`.
This PR introduces a fix that checks whether `prefix` is a string, and if it is, casts it to a list. If anything other than a string is passed this PR changes nothing.
This closes #78 for me, but, there's more to it than I first thought.
I tried to make some tests fail by loading in multiple iterations with a single prefix, but unexpectedly they passed. It seems that this error only appears when loading in files produced by `pkg/diagnostics` - at least, that's what I've found after trying various combinations with the model output I had to hand. As far as I can tell the test suite doesn't come with multiple timestamps of files from `pkg/diagnostics`, so …

Cast `prefix` to list if it isn't already one

---

xmitgcm/test/test_mds_store.py
xmitgcm/utils.py

* possibility to read part of the file, with offset and partial_read
* choice of row/column major order
This will allow the refactor of read_mds by putting the np.fromfile and np.memmap
calls into one generic function

extend capabilities of read_raw_data

---

xmitgcm/mds_store.py
xmitgcm/test/test_mds_store.py
xmitgcm/utils.py

This PR builds on the read_mds and low_level refactoring and mostly differs by the introduction
of the extra_metadata argument. Users of llc configuration are not required to pass extra_metadata
thanks to the *LEGACY* section that default extra_metadata to llc if needed. All tests passed.

refactoring mds_store to include the option to pass extra metadata

---

xmitgcm/mds_store.py
xmitgcm/test/test_mds_store.py
xmitgcm/variables.py

Previously, the files `AngleCS` and `AngleSN` were not read in the llc configuration. So important information was missing.
My only question here is the choice of `SN` and `CS` as the variable names, rather than the more informative `AngleCS` and `AngleSN`. This was chosen by @sambarluc for the curvilinear cartesian  case, so I kept it here. What do people think?

added angles to llc grid coords

---

xmitgcm/mds_store.py
xmitgcm/test/test_utils.py
xmitgcm/utils.py

test on extra_metadata was not working as it was previously defined.
Added a condition on user defined extra_metadata, so that it defaults to the right llc domain
while preserving the ability to force the extra_metadata (needed for ASTE)

Fix bug llc, fixes #102

---

xmitgcm/mds_store.py
xmitgcm/variables.py

This PR specifically address #108 as follows: 
- "extra" grid variables printed from MITgcm/model/src/write_grid.F added to variables.py as one `OrderedDict` called `extra_grid_variables`
- sigma coordinate coefficients are skipped because it's not clear to me where each of these variables exist, but happy to add them if any of you guys have experience
- added routines to mds_store.py 
- _get_extra_grid_variables : this grabs the list of available variables
- _get_extra_grid_prefixes : looks for prefixes in data_dir and returns a list if any of the extra_grid_vars are found
- I assumed these variables are found in data_dir rather than grid_dir because these files are output at run time, and are useful for debugging, while I would picture a users grid_dir to be somewhere on their machine …

Extra grid vars

---

xmitgcm/test/test_utils.py
xmitgcm/test/test_xmitgcm_common.py
xmitgcm/utils.py

fixes #14 
tested with llc90 and aste. there is room to add cube sphere support once #91 is resolved
and it would be also easy to make it work with simpler geometries, although I have not seen
yet the case of users using input grid files in those.

Read mitgrid files

---

xmitgcm/mds_store.py
xmitgcm/test/test_mds_store.py
xmitgcm/variables.py

This PR adds the 3D mask variables maskC/W/S to grid variables by loading the corresponding hFac variable and computing `np.ceil()` to make 0 or 1. I tried to make the meta data according to conventions discussed in #44, let me know what you think. 
This PR (eventually) resolves #44.

Calculate binary masks from hFac variables

---

xmitgcm/mds_store.py
xmitgcm/variables.py

xmitgcm is not compatible with xarray v0.12.0 because OrderedDict has been removed from `xarray.core.pycompat`. See:
* https://github.com/pydata/xarray/pull/2645/commits/fccb917ef442bbb39ff16a643d700ea52c15934c#
* https://github.com/pydata/xarray/issues/2744

Compatibility with xarray v0.12.0

---

xmitgcm/llcreader/llcmodel.py

The variable "metric" wasn't being passed correctly to transform_u_to_v so I was getting the incorrect sign in some of my domain.

fixed sign of metric terms

---

xmitgcm/test/test_mds_store.py

This PR replaces the deprecated `pytest.raises(..., message="...")` by the pytest-suggested recipe.
Fixes #167 .
[Link to the pytest docs.](https://docs.pytest.org/en/4.6-maintenance/deprecations.html#message-parameter-of-pytest-raises)
This is the reason #165 still fails. 
I hope that with these two PRs, tests will become useful again!

Fix deprecation errors in tests.

---

xmitgcm/llcreader/__init__.py
xmitgcm/llcreader/known_models.py
xmitgcm/llcreader/llcmodel.py

Hopefully this will fix the remaining test failures we have related to llcreader. The keyword arguments for fsspec have changed. See https://github.com/intake/filesystem_spec/issues/123 for details.

Fix fsspec keyword arg bug

---

README.rst
doc/development.rst
doc/installation.rst

I think this gets all of the relevant github urls.

rename repo to MITgcm/xmitgcm

---

ci/environment-py27-xarray0.10.9.yml
ci/environment-py27-xarray0.11.3.yml
ci/environment-py27.yml
ci/environment-py35.yml
ci/environment-py36-xarray0.10.9.yml
ci/environment-py36-xarray0.11.3.yml
ci/environment-py36-xarray0.12.0.yml
ci/environment-py36-xarraymaster.yml
ci/environment-py36.yml
setup.py
xmitgcm/file_utils.py
xmitgcm/mds_store.py
xmitgcm/test/test_file_utils.py
xmitgcm/test/test_mds_store.py
xmitgcm/test/test_utils.py
xmitgcm/test/test_xmitgcm_common.py

Hopefully fixes #148. (Alternative to #162)
All the directory listing and matching is placed in the `file_utils.py` modules. These functions use cachetools to cache their output.
I have not actually tested this on a large archive yet. So far I'm just trying to get the tests to pass. I think I have uncovered some weird properties of the tar archives we are using for test data. I want to see what happens on travis.

Use cache for listing directories

---

xmitgcm/mds_store.py

This (seems to) fix the current bug with the python 3.6, xarray master build. It seems that the newest version of `xarray.combine_by_coords` added the option `combine_attrs`, allowing the user to specify how to handle attributes while combining multiple datasets. The default is `no_conflicts`, which in this case causes a problem with the `history` attribute since each dataset corresponds to an iteration (or None for the grid), each of which is different and shows up in this attribute as "created by calling open_mdsdataset(.....)"
It seems that the old default was to simply drop attributes, so that's what I'm setting the option to for a first pass. We could also just drop the attributes before calling `xr.combine_by_coords`, and remove the need for testing.

fix py36 xarray master build

---

doc/llcreader.rst
xmitgcm/llcreader/known_models.py
xmitgcm/llcreader/llcmodel.py
xmitgcm/llcreader/stores.py
xmitgcm/mds_store.py
xmitgcm/test/test_llcreader.py
xmitgcm/variables.py

This PR is designed to give llcreader access to grid information on the ECCO portal (or elsewhere), to hopefully to close #161, close #166, and close #158 (possibly more).
Right now it gets the full grid for LLC 2160 and gets the available grid info on the ECCO portal for LLC 4320, which is some but not all. I was not able access the grid info mentioned by @rabernat in #161, which was [here](https://pangeo-data.github.io/pangeo-datastore/master/ocean/llc4320.html#llc4320-grid)
**vertical grid variables and coordinates**
this got a little tricky since everything is designed to deal with faceted data. I wrote some functions to read these in differently. I adapted the same infrastructure to the 1D variables, even though they could probably be dealt with eagerly (see `_get_1d_chunk` and …

llcreader: get grid info from portal

---

ci/environment-py2.7.yml
setup.py

Current python 2.7 tests break because of zarr, which has not supported python 2 since version 2.3.2. This PR specifies `zarr<=2.3.2` in the ci/environment file.

python 2.7 env with old zarr

---

xmitgcm/mds_store.py

Fixes #229 by skipping conflict checks when merging datasets.
I'm not 100% sure this does not break something, but it didn't break the tests on my machine!

Lazy open_mdsdataset with recent xarray versions.

---

xmitgcm/llcreader/llcmodel.py
xmitgcm/test/test_llcreader.py

Possible fix for #224.
Will travis even run on this repo any more? It seems broken in all our other repos.

Fix llcreader klevels bug

---

xmitgcm/llcreader/llcmodel.py
xmitgcm/test/test_llcreader.py

On a latlon LLC grid some variables have mates. This commit will produce a meaningful error if attempting to use `get_dataset` or `faces_dataset_to_latlon` to load a variable without its mate.
See Github issue #234

feat: IMPLEMENTS CHECKING FOR VARIABLE MATES

---

xmitgcm/variables.py

convention here seems to be
XC=dict(dims=["j", "i"], attrs=dict(
standard_name="longitude", long_name="longitude",
units="degrees_east", coordinate="YC XC")),
some instances fixed where "coordinate" was spelled "coordinates".  May have no effect.

fixed probable typo for 'coordinate' entry in dimensions dictionary

---

.github/workflows/pythonpublish.yaml

This will [hopefully] make it so a release pypi is automatically made when we publish a release on GitHub.

added publish workflow

---

xmitgcm/variables.py

for my ecco-like adjoint simulations, I would like to be able to read the hard coded standard adjoint output (per adjDumpFreq) with xmitgcm. Appending the dict `packages_state_variables` let's me do so.
Also there's s small fix to one variable name and unit.

add a standard set of ADJ variables

---

xmitgcm/variables.py

Now l='lower', u='upper' in the descriptions of four variables: Zl, Zu, k_l, k_u.
@rabernat

fixed mistake with naming of Zl/Zu and k_l/k_u.  

---

xmitgcm/variables.py

fix variable metadata typos

---

.github/workflows/ci.yaml

I noticed my fork's master, xarray-master build failed to pass checks: https://github.com/timothyas/xmitgcm/runs/2344997019
This is fixed by updating the python version specified to GitHub Actions from 3.6 -> 3.7

Minor update xarray master CI workflow

---

xmitgcm/mds_store.py
xmitgcm/test/test_mds_store.py

This PR fixes the `combine_by_coors` call to fix `_swap_dims`.
Closes #265

fix combine_by_coords

---

xmitgcm/llcreader/known_models.py

This fixes issue #278 as PR #192 fixed issue #191, by add SIu/vice to mask_override.

fix masking for SIuice and SIvice in the same way as for oceTAUX/Y

---

xmitgcm/llcreader/llcutils.py

This apparent typo was noted by @mlosch in #278.
It looks severe. However, how could things have possibly worked without it. This really makes me wish we had better test coverage for the llcreader stuff. 🤦

Use correct mask suffixes

---

xmitgcm/test/test_llcreader.py

Updated `test_ecco_portal_iterations` and `test_aste_portal_iterations` so that they don't fail when deprecation warnings are raised.  Currently xarray and distutils are raising DeprecationWarnings we have no control over causing these tests to fails. See also pull request #293

Ignore deprecation warnings
